# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-03 12:01
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('createDate', models.DateField(default=datetime.date.today)),
                ('pubmedID', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('vote', models.IntegerField(default=0)),
                ('commentCount', models.IntegerField(default=0)),
                ('tag', models.CharField(blank=True, choices=[('Cancer immunology', 'Cancer immunology'), ('Cancer Epigenetics', 'Cancer Epigenetics'), ('CRISPR screens', 'CRISPR screens'), ('Drug response and resistance', 'Drug response and resistance')], max_length=10, null=True, verbose_name='tag')),
                ('belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Article', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='website.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='like')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickes', to='website.Article')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.URLField(blank=True, max_length=100, null=True, verbose_name='imgURL')),
                ('nick_name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='nickName')),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin')),
                ('belong_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
