# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-03 14:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='comment',
            name='createDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
