# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-04 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170904_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image_url',
            field=models.CharField(default='/static/img/geek.jpg', max_length=250),
        ),
    ]
