# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-05 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170904_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='profile_image',
            field=models.CharField(default='/static/img/geek.jpg', max_length=250),
        ),
    ]
