# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-07 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170906_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pubmedIDurl',
            field=models.CharField(default='https://www.ncbi.nlm.nih.gov/pubmed/', max_length=20),
        ),
    ]
